# Generated by Django 5.0.6 on 2024-07-31 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_and_exam', '0004_question_choice_sinavi_cozen_kisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testing_choice',
            name='testi_cozen_kisi',
            field=models.ManyToManyField(blank=True, default=None, max_length=100, null=True, related_name='testi_cozen_kisi', to=settings.AUTH_USER_MODEL, verbose_name='testi_cozen_kisi'),
        ),
        migrations.AlterField(
            model_name='question_choice',
            name='sinavi_cozen_kisi',
            field=models.ManyToManyField(blank=True, default=None, max_length=100, null=True, related_name='sinavi_cozen_kisi', to=settings.AUTH_USER_MODEL, verbose_name='sinavi_cozen_kisi'),
        ),
    ]
