# Generated by Django 5.0.6 on 2024-08-01 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_and_exam', '0005_testing_choice_testi_cozen_kisi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tyt_choice',
            name='tyt_cozen_kisi',
            field=models.ManyToManyField(blank=True, default=None, max_length=100, null=True, related_name='tyt_cozen_kisi', to=settings.AUTH_USER_MODEL, verbose_name='tyt_cozen_kisi'),
        ),
        migrations.AlterField(
            model_name='testing_choice',
            name='Class_Choice',
            field=models.CharField(choices=[('9. Sınıf', '9. Sınıf'), ('10. Sınıf', '10. Sınıf'), ('11. Sınıf', '11. Sınıf'), ('12. Sınıf', '12. Sınıf')], max_length=15, null=True, verbose_name='KAÇINCI SINIF SORUSU ?'),
        ),
        migrations.AlterField(
            model_name='tyt_choice',
            name='Lessons_Name',
            field=models.CharField(choices=[('Matematik', 'Matematik'), ('Fizik', 'Fizik'), ('Kimya', 'Kimya'), ('Tarih', 'Tarih'), ('Biyoloji', 'Biyoloji'), ('Coğrafya', 'Coğrafya'), ('Türkçe', 'Türkçe'), ('Din Kültürü ve Ahlak Bilgisi', 'Din Kültürü ve Ahlak Bilgisi')], max_length=100, verbose_name='DERS ADI'),
        ),
    ]
