# Generated by Django 5.0.6 on 2024-08-01 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_and_exam', '0006_tyt_choice_tyt_cozen_kisi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ayt_choice',
            name='ayt_cozen_kisi',
            field=models.ManyToManyField(blank=True, default=None, max_length=100, null=True, related_name='ayt_cozen_kisi', to=settings.AUTH_USER_MODEL, verbose_name='ayt_cozen_kisi'),
        ),
    ]
