# Generated by Django 5.0.6 on 2024-08-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_and_exam', '0007_ayt_choice_ayt_cozen_kisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayt_choice',
            name='Lessons_Name',
            field=models.CharField(choices=[('Matematik', 'Matematik'), ('Türk Dili ve Edebiyatı', 'Türk Dili ve Edebiyatı'), ('Fizik', 'Fizik'), ('Kimya', 'Kimya'), ('Tarih', 'Tarih'), ('Biyoloji', 'Biyoloji'), ('Coğrafya', 'Coğrafya'), ('Din Kültürü ve Ahlak Bilgisi', 'Din Kültürü ve Ahlak Bilgisi')], max_length=100, verbose_name='DERS ADI'),
        ),
    ]
