# Generated by Django 5.0.6 on 2024-05-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='discover/', verbose_name='KEŞFET İÇİN FOTOĞRAF EKLEYİN')),
                ('_text', models.TextField(blank=True, null=True, verbose_name='FOTOĞRAF METNİ EKLEYİN')),
                ('Created_Date', models.DateTimeField(auto_now=True, verbose_name='OLUŞTURMA TARİHİ')),
            ],
        ),
    ]
