# Generated by Django 5.0.6 on 2024-05-13 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=15, verbose_name='Kaçıncı Sınıf Öğretmeni?')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lessons_Name', models.CharField(max_length=100, null=True, verbose_name='Ders Adı')),
                ('Classrooms_Name', models.ManyToManyField(related_name='lesson_name', to='question.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lessons', models.CharField(max_length=50, null=True, verbose_name='Ders Adı')),
                ('Question', models.TextField(verbose_name='Soru')),
                ('Ticket', models.TextField(blank=True, null=True, verbose_name='Çoktan Seçmeli İçin Etiket Adı')),
                ('Cell_1', models.TextField(blank=True, null=True, verbose_name='HÜCRE 1')),
                ('Cell_2', models.TextField(blank=True, null=True, verbose_name='HÜCRE 2')),
                ('Choice_A', models.TextField(blank=True, null=True, verbose_name='A Şıkkı')),
                ('Choice_B', models.TextField(blank=True, null=True, verbose_name='B Şıkkı')),
                ('Choice_C', models.TextField(blank=True, null=True, verbose_name='C Şıkkı')),
                ('Choice_D', models.TextField(blank=True, null=True, verbose_name='D Şıkkı')),
                ('Choice_E', models.TextField(blank=True, null=True, verbose_name='E Şıkkı')),
                ('Answer', models.TextField(verbose_name='Cevap')),
                ('Classroom', models.CharField(max_length=10, null=True, verbose_name='Kaçıncı Sınıf Sorusu?')),
                ('Topics_Name', models.CharField(max_length=100, null=True, verbose_name='Konu Adı')),
                ('Question_Types', models.CharField(max_length=20, null=True, verbose_name='SORU TİPLERİ')),
                ('Level', models.CharField(blank=True, default='KOLAY', max_length=6)),
                ('Caption', models.TextField(blank=True, max_length=150, null=True, verbose_name='Açıklama')),
                ('Question_Image', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Soruya Fotoğraf Ekleyin')),
                ('Created_Date', models.DateTimeField(auto_now=True, verbose_name='Oluşturma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Soruyu Yazan')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(blank=True, null=True, verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşturma Tarihi')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='YORUM YAPAN')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.question', verbose_name='Yorum Yapılan Makale')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topics_Name', models.CharField(max_length=100, null=True, verbose_name='Konu Adı')),
                ('Lessons_Name', models.ManyToManyField(related_name='topics_name', to='question.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='SORUYU BEĞENEN')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='question.question', verbose_name='BEĞENİ YAPILAN SORU')),
            ],
            options={
                'unique_together': {('author', 'question')},
            },
        ),
    ]
