# Generated by Django 5.0.6 on 2024-05-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name_plural': 'SINIF EKLEME'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'YORUM EKLEME'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'DERS EKLEME'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': 'BEĞENME İŞLEMİ'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'SORU EKLEME'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': 'KONU EKLEME'},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
