# Generated by Django 5.0.6 on 2024-05-13 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_items', models.IntegerField(null=True, verbose_name='Soru Id:')),
                ('Lessons', models.CharField(max_length=50, null=True, verbose_name='Ders Adı')),
                ('Question', models.TextField(null=True, verbose_name='Soru')),
                ('Choice_A', models.TextField(blank=True, null=True, verbose_name='A Şıkkı')),
                ('Choice_B', models.TextField(blank=True, null=True, verbose_name='B Şıkkı')),
                ('Choice_C', models.TextField(blank=True, null=True, verbose_name='C Şıkkı')),
                ('Choice_D', models.TextField(blank=True, null=True, verbose_name='D Şıkkı')),
                ('Choice_E', models.TextField(blank=True, null=True, verbose_name='E Şıkkı')),
                ('Answer', models.TextField(null=True, verbose_name='Cevap')),
                ('Classroom', models.CharField(max_length=10, null=True, verbose_name='Kaçıncı Sınıf Sorusu?')),
                ('Topics_Name', models.CharField(max_length=100, null=True, verbose_name='Konu Adı')),
                ('Question_Types', models.CharField(max_length=20, null=True, verbose_name='SORU TİPLERİ')),
                ('Level', models.CharField(blank=True, default='KOLAY', max_length=6)),
                ('Question_Image', models.ImageField(blank=True, null=True, upload_to='cart_images/', verbose_name='Soruya Fotoğraf Ekleyin')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşturma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sepete Ekleyen')),
            ],
        ),
        migrations.CreateModel(
            name='CartExamTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(blank=True, max_length=100, verbose_name='Sınav Adı')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşturma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sınavı Adını Oluşturan')),
            ],
        ),
    ]
