# Generated by Django 5.0.6 on 2024-05-13 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=400, verbose_name='Okul Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatars', models.ImageField(null=True, upload_to='user/')),
                ('biographys', models.CharField(max_length=150, null=True)),
                ('mail_adress', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_phone', models.CharField(max_length=11, null=True, unique=True, verbose_name='Cep Telefonu')),
                ('social_media_facebook', models.TextField(blank=True, null=True, verbose_name='Facebook Sosyal Medya')),
                ('social_media_twitter', models.TextField(blank=True, null=True, verbose_name='Twitter Sosyal Medya')),
                ('social_media_instagram', models.TextField(blank=True, null=True, verbose_name='İnstagram Sosyal Medya')),
                ('social_media_tiktok', models.TextField(blank=True, null=True, verbose_name='Tiktok Sosyal Medya')),
                ('user_types', models.CharField(choices=[('Manager', 'Manager'), ('Assistant', 'Assistant'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Parents', 'Parents'), ('Publisher', 'Publisher')], default='Teacher', max_length=20)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='KULLANICI')),
                ('classrooms', models.ManyToManyField(related_name='classroom_name', to='question.classroom', verbose_name='Kaçıncı Sınıf Öğretmeni?')),
                ('followers', models.ManyToManyField(default=0, related_name='follower_users', to=settings.AUTH_USER_MODEL, verbose_name='Takipçi')),
                ('following', models.ManyToManyField(default=0, related_name='following_users', to=settings.AUTH_USER_MODEL, verbose_name='Takip Etme')),
                ('lessons', models.ManyToManyField(related_name='teacher_lessons', to='question.lesson')),
                ('schools', models.ManyToManyField(related_name='school_name', to='user.school', verbose_name='Okul Adı')),
            ],
        ),
    ]
