# Generated by Django 5.0 on 2024-06-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_author'),
        ('user', '0004_alter_profile_options_alter_school_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatars',
            field=models.ImageField(default='user/default_user.jpg', null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lessons',
            field=models.ManyToManyField(blank=True, null=True, related_name='teacher_lessons', to='question.lesson'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='schools',
            field=models.ManyToManyField(default=None, related_name='school_name', to='user.school', verbose_name='Okul Adı'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_types',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Assistant', 'Assistant'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Parents', 'Parents'), ('Publisher', 'Publisher')], default='Student', max_length=20),
        ),
    ]
