# Generated by Django 5.0.6 on 2024-08-10 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_avatars_alter_profile_lessons_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribeEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_one', models.IntegerField(verbose_name='Birinci Ödeme Planı')),
                ('subscriber_two', models.IntegerField(verbose_name='İkinci Ödeme Planı')),
                ('subscriber_three', models.IntegerField(verbose_name='Üçüncü Ödeme Planı')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscribe_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Abonelik Düzenlemesi',
                'verbose_name_plural': 'Kullanıcı Abonelik Düzenlemeleri',
                'ordering': ['author'],
            },
        ),
    ]
