# Generated by Django 5.0.6 on 2024-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usersubscribeedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribeedit',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi'),
        ),
    ]
