# Generated by Django 5.0.6 on 2024-08-10 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usersubscribeedit_subscriber_for_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscribeedit',
            old_name='subscriber_for',
            new_name='subscriber_four',
        ),
    ]
